export const ALL_CLIENTES_REQUEST = "ALL_CLIENTES_REQUEST"
export const ALL_CLIENTES_SUCCESS = "ALL_CLIENTES_SUCCESS"
export const ALL_CLIENTES_FAIL = "ALL_CLIENTES_FAIL"

export const CLIENTE_DETAILS_REQUEST="CLIENTE_DETAILS_REQUEST"
export const CLIENTE_DETAILS_SUCCESS="CLIENTE_DETAILS_SUCCESS"
export const CLIENTE_DETAILS_FAIL="CLIENTE_DETAILS_FAIL"

export const NEW_CLIENTE_REQUEST = "NEW_CLIENTE_REQUEST"
export const NEW_CLIENTE_SUCCESS = "NEW_CLIENTE_SUCCESS"
export const NEW_CLIENTE_FAIL = "NEW_CLIENTE_FAIL"
export const NEW_CLIENTE_RESET = "NEW_CLIENTE_RESET"

export const DELETE_CLIENTE_REQUEST = "DELETE_CLIENTE_REQUEST"
export const DELETE_CLIENTE_SUCCESS = "DELETE_CLIENTE_SUCCESS"
export const DELETE_CLIENTE_FAIL = "DELETE_CLIENTE_FAIL"
export const DELETE_CLIENTE_RESET = "DELETE_CLIENTE_RESET"

export const UPDATE_CLIENTE_REQUEST = "UPDATE_CLIENTE_REQUEST"
export const UPDATE_CLIENTE_SUCCESS = "UPDATE_CLIENTE_SUCCESS"
export const UPDATE_CLIENTE_FAIL = "UPDATE_CLIENTE_FAIL"
export const UPDATE_CLIENTE_RESET = "UPDATE_CLIENTE_RESET"


export const CLEAR_ERRORS = "CLEAR_ERRORS"