export const ALL_GASTOS_REQUEST = "ALL_GASTOS_REQUEST"
export const ALL_GASTOS_SUCCESS = "ALL_GASTOS_SUCCESS"
export const ALL_GASTOS_FAIL = "ALL_GASTOS_FAIL"

export const GASTO_DETAILS_REQUEST="GASTO_DETAILS_REQUEST"
export const GASTO_DETAILS_SUCCESS="GASTO_DETAILS_SUCCESS"
export const GASTO_DETAILS_FAIL="GASTO_DETAILS_FAIL"

export const NEW_GASTO_REQUEST = "NEW_GASTO_REQUEST"
export const NEW_GASTO_SUCCESS = "NEW_GASTO_SUCCESS"
export const NEW_GASTO_FAIL = "NEW_GASTO_FAIL"
export const NEW_GASTO_RESET = "NEW_GASTO_RESET"

export const DELETE_GASTO_REQUEST = "DELETE_GASTO_REQUEST"
export const DELETE_GASTO_SUCCESS = "DELETE_GASTO_SUCCESS"
export const DELETE_GASTO_FAIL = "DELETE_GASTO_FAIL"
export const DELETE_GASTO_RESET = "DELETE_GASTO_RESET"

export const UPDATE_GASTO_REQUEST = "UPDATE_GASTO_REQUEST"
export const UPDATE_GASTO_SUCCESS = "UPDATE_GASTO_SUCCESS"
export const UPDATE_GASTO_FAIL = "UPDATE_GASTO_FAIL"
export const UPDATE_GASTO_RESET = "UPDATE_GASTO_RESET"





export const CLEAR_ERRORS = "CLEAR_ERRORS"