
export const ALL_INGRESOS_REQUEST = "ALL_INGRESOS_REQUEST"
export const ALL_INGRESOS_SUCCESS = "ALL_INGRESOS_SUCCESS"
export const ALL_INGRESOS_FAIL = "ALL_INGRESOS_FAIL"

export const INGRESO_DETAILS_REQUEST="INGRESO_DETAILS_REQUEST"
export const INGRESO_DETAILS_SUCCESS="INGRESO_DETAILS_SUCCESS"
export const INGRESO_DETAILS_FAIL="INGRESO_DETAILS_FAIL"

export const NEW_INGRESO_REQUEST = "NEW_INGRESO_REQUEST"
export const NEW_INGRESO_SUCCESS = "NEW_INGRESO_SUCCESS"
export const NEW_INGRESO_FAIL = "NEW_INGRESO_FAIL"
export const NEW_INGRESO_RESET = "NEW_INGRESO_RESET"

export const DELETE_INGRESO_REQUEST = "DELETE_INGRESO_REQUEST"
export const DELETE_INGRESO_SUCCESS = "DELETE_INGRESO_SUCCESS"
export const DELETE_INGRESO_FAIL = "DELETE_INGRESO_FAIL"
export const DELETE_INGRESO_RESET = "DELETE_INGRESO_RESET"

export const UPDATE_INGRESO_REQUEST = "UPDATE_INGRESO_REQUEST"
export const UPDATE_INGRESO_SUCCESS = "UPDATE_INGRESO_SUCCESS"
export const UPDATE_INGRESO_FAIL = "UPDATE_INGRESO_FAIL"
export const UPDATE_INGRESO_RESET = "UPDATE_INGRESO_RESET"





export const CLEAR_ERRORS = "CLEAR_ERRORS"