export const ALL_PEDIDOS_REQUEST = "ALL_PEDIDOS_REQUEST"
export const ALL_PEDIDOS_SUCCESS = "ALL_PEDIDOS_SUCCESS"
export const ALL_PEDIDOS_FAIL = "ALL_PEDIDOS_FAIL"


export const ALL_PEDIDOS_CLIENTE_REQUEST = "ALL_PEDIDOS_CLIENTE_REQUEST"
export const ALL_PEDIDOS_CLIENTE_SUCCESS = "ALL_PEDIDOS_CLIENTE_SUCCESS"
export const ALL_PEDIDOS_CLIENTE_FAIL = "ALL_PEDIDOS_CLIENTE_FAIL"

export const PEDIDO_DETAILS_REQUEST="PEDIDO_DETAILS_REQUEST"
export const PEDIDO_DETAILS_SUCCESS="PEDIDO_DETAILS_SUCCESS"
export const PEDIDO_DETAILS_FAIL="PEDIDO_DETAILS_FAIL"

export const NEW_PEDIDO_REQUEST = "NEW_PEDIDO_REQUEST"
export const NEW_PEDIDO_SUCCESS = "NEW_PEDIDO_SUCCESS"
export const NEW_PEDIDO_FAIL = "NEW_PEDIDO_FAIL"
export const NEW_PEDIDO_RESET = "NEW_PEDIDO_RESET"

export const DELETE_PEDIDO_REQUEST = "DELETE_PEDIDO_REQUEST"
export const DELETE_PEDIDO_SUCCESS = "DELETE_PEDIDO_SUCCESS"
export const DELETE_PEDIDO_FAIL = "DELETE_PEDIDO_FAIL"
export const DELETE_PEDIDO_RESET = "DELETE_PEDIDO_RESET"

export const UPDATE_PEDIDO_REQUEST = "UPDATE_PEDIDO_REQUEST"
export const UPDATE_PEDIDO_SUCCESS = "UPDATE_PEDIDO_SUCCESS"
export const UPDATE_PEDIDO_FAIL = "UPDATE_PEDIDO_FAIL"
export const UPDATE_PEDIDO_RESET = "UPDATE_PEDIDO_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"