export const ALL_MOVIMIENTO_STOCK_REQUEST = "ALL_MOVIMIENTO_STOCK_REQUEST"
export const ALL_MOVIMIENTO_STOCK_SUCCESS = "ALL_MOVIMIENTO_STOCK_SUCCESS"
export const ALL_MOVIMIENTO_STOCK_FAIL = "ALL_MOVIMIENTO_STOCK_FAIL"

export const NEW_MOVIMIENTO_STOCK_REQUEST = "NEW_MOVIMIENTO_STOCK_REQUEST"
export const NEW_MOVIMIENTO_STOCK_SUCCESS = "NEW_MOVIMIENTO_STOCK_SUCCESS"
export const NEW_MOVIMIENTO_STOCK_FAIL = "NEW_MOVIMIENTO_STOCK_FAIL"
export const NEW_MOVIMIENTO_STOCK_RESET = "NEW_MOVIMIENTO_STOCK_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"